/**
 * Region mapping utility for countries
 * Maps country codes to their respective regions for the comparison engine
 */

export const REGIONS = {
  'AFRICA': 'Africa',
  'ASIA': 'Asia',
  'EUROPE': 'Europe',
  'NORTH_AMERICA': 'North America',
  'SOUTH_AMERICA': 'South America',
  'OCEANIA': 'Oceania',
  'MIDDLE_EAST': 'Middle East'
}

// Country code to region mapping
export const COUNTRY_REGIONS = {
  // Africa
  'DZA': REGIONS.AFRICA, 'AGO': REGIONS.AFRICA, 'BEN': REGIONS.AFRICA, 'BWA': REGIONS.AFRICA,
  'BFA': REGIONS.AFRICA, 'BDI': REGIONS.AFRICA, 'CMR': REGIONS.AFRICA, 'CPV': REGIONS.AFRICA,
  'CAF': REGIONS.AFRICA, 'TCD': REGIONS.AFRICA, 'COM': REGIONS.AFRICA, 'COG': REGIONS.AFRICA,
  'COD': REGIONS.AFRICA, 'CIV': REGIONS.AFRICA, 'DJI': REGIONS.AFRICA, 'EGY': REGIONS.AFRICA,
  'GNQ': REGIONS.AFRICA, 'ERI': REGIONS.AFRICA, 'ETH': REGIONS.AFRICA, 'GAB': REGIONS.AFRICA,
  'GMB': REGIONS.AFRICA, 'GHA': REGIONS.AFRICA, 'GIN': REGIONS.AFRICA, 'GNB': REGIONS.AFRICA,
  'KEN': REGIONS.AFRICA, 'LSO': REGIONS.AFRICA, 'LBR': REGIONS.AFRICA, 'LBY': REGIONS.AFRICA,
  'MDG': REGIONS.AFRICA, 'MWI': REGIONS.AFRICA, 'MLI': REGIONS.AFRICA, 'MRT': REGIONS.AFRICA,
  'MUS': REGIONS.AFRICA, 'MAR': REGIONS.AFRICA, 'MOZ': REGIONS.AFRICA, 'NAM': REGIONS.AFRICA,
  'NER': REGIONS.AFRICA, 'NGA': REGIONS.AFRICA, 'RWA': REGIONS.AFRICA, 'STP': REGIONS.AFRICA,
  'SEN': REGIONS.AFRICA, 'SYC': REGIONS.AFRICA, 'SLE': REGIONS.AFRICA, 'SOM': REGIONS.AFRICA,
  'ZAF': REGIONS.AFRICA, 'SSD': REGIONS.AFRICA, 'SDN': REGIONS.AFRICA, 'SWZ': REGIONS.AFRICA,
  'TZA': REGIONS.AFRICA, 'TGO': REGIONS.AFRICA, 'TUN': REGIONS.AFRICA, 'UGA': REGIONS.AFRICA,
  'ZMB': REGIONS.AFRICA, 'ZWE': REGIONS.AFRICA,

  // Asia
  'AFG': REGIONS.ASIA, 'ARM': REGIONS.ASIA, 'AZE': REGIONS.ASIA, 'BHR': REGIONS.MIDDLE_EAST,
  'BGD': REGIONS.ASIA, 'BTN': REGIONS.ASIA, 'BRN': REGIONS.ASIA, 'KHM': REGIONS.ASIA,
  'CHN': REGIONS.ASIA, 'CYP': REGIONS.ASIA, 'GEO': REGIONS.ASIA, 'IND': REGIONS.ASIA,
  'IDN': REGIONS.ASIA, 'IRN': REGIONS.MIDDLE_EAST, 'IRQ': REGIONS.MIDDLE_EAST, 'ISR': REGIONS.MIDDLE_EAST,
  'JPN': REGIONS.ASIA, 'JOR': REGIONS.MIDDLE_EAST, 'KAZ': REGIONS.ASIA, 'KWT': REGIONS.MIDDLE_EAST,
  'KGZ': REGIONS.ASIA, 'LAO': REGIONS.ASIA, 'LBN': REGIONS.MIDDLE_EAST, 'MYS': REGIONS.ASIA,
  'MDV': REGIONS.ASIA, 'MNG': REGIONS.ASIA, 'MMR': REGIONS.ASIA, 'NPL': REGIONS.ASIA,
  'PRK': REGIONS.ASIA, 'OMN': REGIONS.MIDDLE_EAST, 'PAK': REGIONS.ASIA, 'PHL': REGIONS.ASIA,
  'QAT': REGIONS.MIDDLE_EAST, 'SAU': REGIONS.MIDDLE_EAST, 'SGP': REGIONS.ASIA, 'KOR': REGIONS.ASIA,
  'LKA': REGIONS.ASIA, 'SYR': REGIONS.MIDDLE_EAST, 'TWN': REGIONS.ASIA, 'TJK': REGIONS.ASIA,
  'THA': REGIONS.ASIA, 'TLS': REGIONS.ASIA, 'TUR': REGIONS.ASIA, 'TKM': REGIONS.ASIA,
  'ARE': REGIONS.MIDDLE_EAST, 'UZB': REGIONS.ASIA, 'VNM': REGIONS.ASIA, 'YEM': REGIONS.MIDDLE_EAST,

  // Europe
  'ALB': REGIONS.EUROPE, 'AND': REGIONS.EUROPE, 'AUT': REGIONS.EUROPE, 'BLR': REGIONS.EUROPE,
  'BEL': REGIONS.EUROPE, 'BIH': REGIONS.EUROPE, 'BGR': REGIONS.EUROPE, 'HRV': REGIONS.EUROPE,
  'CZE': REGIONS.EUROPE, 'DNK': REGIONS.EUROPE, 'EST': REGIONS.EUROPE, 'FIN': REGIONS.EUROPE,
  'FRA': REGIONS.EUROPE, 'DEU': REGIONS.EUROPE, 'GRC': REGIONS.EUROPE, 'HUN': REGIONS.EUROPE,
  'ISL': REGIONS.EUROPE, 'IRL': REGIONS.EUROPE, 'ITA': REGIONS.EUROPE, 'XKX': REGIONS.EUROPE,
  'LVA': REGIONS.EUROPE, 'LIE': REGIONS.EUROPE, 'LTU': REGIONS.EUROPE, 'LUX': REGIONS.EUROPE,
  'MLT': REGIONS.EUROPE, 'MDA': REGIONS.EUROPE, 'MCO': REGIONS.EUROPE, 'MNE': REGIONS.EUROPE,
  'NLD': REGIONS.EUROPE, 'MKD': REGIONS.EUROPE, 'NOR': REGIONS.EUROPE, 'POL': REGIONS.EUROPE,
  'PRT': REGIONS.EUROPE, 'ROU': REGIONS.EUROPE, 'RUS': REGIONS.EUROPE, 'SMR': REGIONS.EUROPE,
  'SRB': REGIONS.EUROPE, 'SVK': REGIONS.EUROPE, 'SVN': REGIONS.EUROPE, 'ESP': REGIONS.EUROPE,
  'SWE': REGIONS.EUROPE, 'CHE': REGIONS.EUROPE, 'UKR': REGIONS.EUROPE, 'GBR': REGIONS.EUROPE,
  'VAT': REGIONS.EUROPE,

  // North America
  'ATG': REGIONS.NORTH_AMERICA, 'BHS': REGIONS.NORTH_AMERICA, 'BRB': REGIONS.NORTH_AMERICA,
  'BLZ': REGIONS.NORTH_AMERICA, 'CAN': REGIONS.NORTH_AMERICA, 'CRI': REGIONS.NORTH_AMERICA,
  'CUB': REGIONS.NORTH_AMERICA, 'DMA': REGIONS.NORTH_AMERICA, 'DOM': REGIONS.NORTH_AMERICA,
  'SLV': REGIONS.NORTH_AMERICA, 'GRD': REGIONS.NORTH_AMERICA, 'GTM': REGIONS.NORTH_AMERICA,
  'HTI': REGIONS.NORTH_AMERICA, 'HND': REGIONS.NORTH_AMERICA, 'JAM': REGIONS.NORTH_AMERICA,
  'MEX': REGIONS.NORTH_AMERICA, 'NIC': REGIONS.NORTH_AMERICA, 'PAN': REGIONS.NORTH_AMERICA,
  'KNA': REGIONS.NORTH_AMERICA, 'LCA': REGIONS.NORTH_AMERICA, 'VCT': REGIONS.NORTH_AMERICA,
  'TTO': REGIONS.NORTH_AMERICA, 'USA': REGIONS.NORTH_AMERICA,

  // South America
  'ARG': REGIONS.SOUTH_AMERICA, 'BOL': REGIONS.SOUTH_AMERICA, 'BRA': REGIONS.SOUTH_AMERICA,
  'CHL': REGIONS.SOUTH_AMERICA, 'COL': REGIONS.SOUTH_AMERICA, 'ECU': REGIONS.SOUTH_AMERICA,
  'GUY': REGIONS.SOUTH_AMERICA, 'PRY': REGIONS.SOUTH_AMERICA, 'PER': REGIONS.SOUTH_AMERICA,
  'SUR': REGIONS.SOUTH_AMERICA, 'URY': REGIONS.SOUTH_AMERICA, 'VEN': REGIONS.SOUTH_AMERICA,

  // Oceania
  'AUS': REGIONS.OCEANIA, 'FJI': REGIONS.OCEANIA, 'KIR': REGIONS.OCEANIA, 'MHL': REGIONS.OCEANIA,
  'FSM': REGIONS.OCEANIA, 'NRU': REGIONS.OCEANIA, 'NZL': REGIONS.OCEANIA, 'PLW': REGIONS.OCEANIA,
  'PNG': REGIONS.OCEANIA, 'WSM': REGIONS.OCEANIA, 'SLB': REGIONS.OCEANIA, 'TON': REGIONS.OCEANIA,
  'TUV': REGIONS.OCEANIA, 'VUT': REGIONS.OCEANIA
}

/**
 * Get region for a country by country code
 * @param {string} countryCode - ISO 3-letter country code
 * @returns {string} Region name or 'Unknown' if not found
 */
export function getCountryRegion(countryCode) {
  return COUNTRY_REGIONS[countryCode] || 'Unknown'
}

/**
 * Get all countries grouped by region
 * @param {Array} countries - Array of country objects with countryCode property
 * @returns {Object} Object with regions as keys and arrays of countries as values
 */
export function groupCountriesByRegion(countries) {
  const grouped = {}
  
  countries.forEach(country => {
    const region = getCountryRegion(country.countryCode)
    if (!grouped[region]) {
      grouped[region] = []
    }
    grouped[region].push(country)
  })
  
  // Sort countries within each region alphabetically
  Object.keys(grouped).forEach(region => {
    grouped[region].sort((a, b) => a.countryName.localeCompare(b.countryName))
  })
  
  return grouped
}

/**
 * Get all unique regions from a list of countries
 * @param {Array} countries - Array of country objects with countryCode property
 * @returns {Array} Array of unique region names sorted alphabetically
 */
export function getUniqueRegions(countries) {
  const regions = new Set()
  countries.forEach(country => {
    regions.add(getCountryRegion(country.countryCode))
  })
  return Array.from(regions).sort()
}